global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:4000']

  - job_name: 'user-service-1'
    static_configs:
      - targets: ['user-service-1:5000']

  - job_name: 'booking-service-1'
    static_configs:
      - targets: ['booking-service-1:5003']

